name: CICD
on: 
  workflow_dispatch:
  push:
   branches: main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: clone the repository
        uses: actions/checkout@v4.1.2
      - name: step2
        run: ls -l
      - name: Set up JDK 11 
        uses: actions/setup-java@v3
        with:
            java-version: '11'
            distribution: 'temurin'
